mapping_superstore = {
    "tiernahrung": "Tiere",
    "hundefutter": "Tiere",
    "katzenfutter": "Tiere",
    "haustierbedarf": "Tiere",
    "tierzubehör": "Tiere",
    "haustierpflege": "Tiere",
    "tiermedizin": "Tiere",
    "tierkäfige": "Tiere",
    "vogelkäfig": "Tiere",
    "nagerfutter": "Tiere",
    "parfum": "Parfum",
    "parfümflasche": "Parfum",
    "damendüfte": "Parfum",
    "herrendüfte": "Parfum",
    "duft": "Parfum",
    "eau de": "Parfum",
    "makeup": "Makeup",
    "puder": "Makeup",
    "highlighter": "Makeup",
    "blush": "Makeup",
    "lidschadden": "Makeup",
    "kajal": "Makeup",
    "lippenstift": "Makeup",
    "mascara": "Makeup",
    "foundation": "Makeup",
    "rouge": "Makeup",
    "babywindeln": "Baby",
    "windel": "Baby",
    "wickeltasche": "Baby",
    "baby": "Baby",
    "babyöl": "Baby",
    "babybrei": "Baby",
    "babyspielzeug": "Baby",
    "babymode": "Baby",
    "lebensmittel": "Lebensmittel und Ernährung",
    "lebensmittelgeschäft": "Lebensmittel und Ernährung",
    "biolebensmittel": "Lebensmittel und Ernährung",
    "frischeprodukte": "Lebensmittel und Ernährung",
    "veganeprodukte": "Lebensmittel und Ernährung",
    "hygieneprodukte": "Hygiene",
    "toilettenpapier": "Hygiene",
    "handdesinfektionsmittel": "Hygiene",
    "seife": "Hygiene",
    "gesichtsmasken": "Hygiene",
    "deo": "Hygiene",
    "rasierer": "Hygiene",
    "shampoo": "Hygiene",
    "zahn": "Hygiene",
    "dusch": "Hygiene",
    "fotokameras": "Foto",
    "fotografieausrüstung": "Foto",
    "kameraobjektive": "Foto",
    "fotostudio": "Foto",
    "gesundheit": "Gesundheit",
    "vitamine": "Gesundheit",
    "schnupfen": "Gesundheit",
    "durchfall": "Gesundheit",
    "husten": "Gesundheit",
    "grippe": "Gesundheit",
    "magen": "Gesundheit",
    "fieber": "Gesundheit",
    "pflaster": "Gesundheit",
    "schmerzmittel": "Gesundheit",
    "nahrungsergänzungsmittel": "Gesundheit",
    "medizinprodukte": "Gesundheit",
    "apfel" : "Obst",
    "äpfel" : "Obst",
    "banane" : "Obst",
    "birne" : "Obst",
    "avocado" : "Obst",
    "erdbeere" : "Obst",
    "orange" : "Obst",
    "traube" : "Obst",
    "kirsche" : "Obst",
    "beeren" : "Obst",
    "ananas" : "Obst",
    "mango" : "Obst",
    "melone" : "Obst",
    "limette" : "Obst",
    "zitrone" : "Obst",
    "pfirsich" : "Obst",
    "gurke" : "Gemüse",
    "zwiebel" : "Gemüse",
    "tomate" : "Gemüse",
    "kartoffel" : "Gemüse",
    "karotte" : "Gemüse",
    "kohl" : "Gemüse",
    "pilz" : "Gemüse",
    "erbse" : "Gemüse",
    "spinat" : "Gemüse",
    "brokkoli" : "Gemüse",
    "salat" : "Gemüse",
    "quark" : "Molkerei",
    "butter" : "Molkerei",
    "joghurt" : "Molkerei",
    "käse" : "Molkerei",
    "rahm" : "Molkerei",
    "sahne": "Molkerei",
    "oberst": "Molkerei",
    "eier" : "Food",
    "nudel" : "Food",
    "mehl": "Food",
    "öl" : "Food",
    "nutella" : "Food",
    "marmelade" : "Food",
    "honig" : "Food",
    "sosse" : "Food",
    "soße" : "Food",
    "brot" : "Food",
    "bröt" : "Food",
    "zucker" : "Food",
    "gewürz" : "Food",
    "konserv" : "Food",
    "papier" : "Non-Food",
    "parfum" : "Non-Food",
    "spül" : "Non-Food",
    "schnitzel" : "Fleisch",
    "brust" : "Fleisch",
    "kotelett" : "Fleisch",
    "steak" : "Fleisch",
    "schenkel" : "Fleisch",
    "speck" : "Fleisch",
    "wurst" : "Fleisch",
    "würst" : "Fleisch",
    "schinken" : "Fleisch",
    "salami" : "Fleisch",
    "wiener" : "Fleisch",
    "bauch" : "Fleisch",
    "fleisch" : "Fleisch",
    "hühnchen" : "Fleisch",
    "hähnchen" : "Fleisch",
    "huhn" : "Fleisch",
    "fisch" : "Fleisch",
    "lachs": "Fleisch",
    "hering": "Fleisch",
    "thunfisch": "Fleisch",
    "makrele": "Fleisch",
    "forelle": "Fleisch",
    "schokolade" : "Snacks",
    "gummibären" : "Snacks",
    "jumpys" : "Snacks",
    "chips" : "Snacks",
    "salzstangen" : "Snacks",
    "keks" : "Snacks",
    "flake" : "Snacks",
    "snack" : "Snacks",
    "pflanz" : "Pflanzen",
    "orchide" : "Pflanzen",
    "kaktus": "Pflanzen",
    "fanta" : "Getränke",
    "cola" : "Getränke",
    "saft" : "Getränke",
    "limonade" : "Getränke",
    "tee" : "Getränke",
    "wasser" : "Getränke",
    "shake" : "Getränke",
    "schorle" : "Getränke",
    "energy" : "Getränke",
    "getränk" : "Getränke",
    "bier" : "Getränke",
    "wodka" : "Getränke",
    "schnaps" : "Getränke",
    "likör" : "Getränke",
    "weinbr" : "Getränke"
}

mapping_dm = {
    "baby": "Baby",
    "müsli": "Food",
    "makeup": "MakeUp",
    "parfum" : "Parfum",
    "MAC Cosmetics" : "makeup",
    "Maybelline" : "makeup",
    "oreal" : "makeup",
    "Urban Decay" : "makeup",
    "tee" : "Getränke",
    "mandelmus" : "Getränke",
    "haushalt" : "Haushalt",
    "creme" : "Creme",
    "müsli" : "Food",
    "nudel" : "food",
    "badesalz" : "badesalz",
    "shampoo" : "Haare",
    "balsam" : "Gesundheit",
    "schwanger" : "Gesundheit",
    "mutter" : "Gesundheit"
}

mapping_baumarkt = {
    "rasenmäher": "Garten und Freizeit",
    "gartengeräte": "Garten und Freizeit",
    "gartenmöbel": "Garten und Freizeit",
    "blumenkübel": "Garten und Freizeit",
    "grill": "Garten und Freizeit",
    "swimmingpool": "Garten und Freizeit",
    "gartenbeleuchtung": "Garten und Freizeit",
    "sonnenschirm": "Garten und Freizeit",
    "gartenzaun": "Garten und Freizeit",
    "gartenpflanzen": "Garten und Freizeit",
    "gartenhaus": "Garten und Freizeit",
    "gartenwerkzeug": "Garten und Freizeit",
    "hängematte": "Garten und Freizeit",
    "gartenbrunnen": "Garten und Freizeit",
    "gartenteich": "Garten und Freizeit",
    "bauholz": "Bauen und Renovieren",
    "bauwerkzeuge": "Bauen und Renovieren",
    "baufolie": "Bauen und Renovieren",
    "dachziegel": "Bauen und Renovieren",
    "bauanleitung": "Bauen und Renovieren",
    "bauschaum": "Bauen und Renovieren",
    "baustoffe": "Bauen und Renovieren",
    "renovierungsmaterial": "Bauen und Renovieren",
    "bautreppe": "Bauen und Renovieren",
    "bauanstrich": "Bauen und Renovieren",
    "trockenbau": "Bauen und Renovieren",
    "baucontainer": "Bauen und Renovieren",
    "bauwagen": "Bauen und Renovieren",
    "bauhelm": "Bauen und Renovieren",
    "bauschrauben": "Bauen und Renovieren",
    "holzbretter": "Holz",
    "holzplatten": "Holz",
    "holzlack": "Holz",
    "sperrholz": "Holz",
    "holzleisten": "Holz",
    "holzdübel": "Holz",
    "holzschnitzel": "Holz",
    "holzbeize": "Holz",
    "holzschutz": "Holz",
    "holzpfosten": "Holz",
    "brennholz": "Holz",
    "holzwerkstatt": "Holz",
    "holzsäge": "Holz",
    "holzhammer": "Holz",
    "holzfurnier": "Holz",
    "bohrmaschine": "Werkzeug und Maschinen",
    "schraubendreher": "Werkzeug und Maschinen",
    "akkuschrauber": "Werkzeug und Maschinen",
    "säge": "Werkzeug und Maschinen",
    "werkzeugkoffer": "Werkzeug und Maschinen",
    "schleifmaschine": "Werkzeug und Maschinen",
    "handkreissäge": "Werkzeug und Maschinen",
    "winkelschleifer": "Werkzeug und Maschinen",
    "schraubzwingen": "Werkzeug und Maschinen",
    "werkbank": "Werkzeug und Maschinen",
    "bohrer": "Werkzeug und Maschinen",
    "schrauben": "Werkzeug und Maschinen",
    "schweißgerät": "Werkzeug und Maschinen",
    "tischkreissäge": "Werkzeug und Maschinen",
    "elektrowerkzeuge": "Werkzeug und Maschinen",
    "elektrokabel": "Elektro und Technik",
    "steckdosen": "Elektro und Technik",
    "elektrowerkzeug": "Elektro und Technik",
    "lichtschalter": "Elektro und Technik",
    "elektroinstallation": "Elektro und Technik",
    "led-leuchten": "Elektro und Technik",
    "elektroinstallationssatz": "Elektro und Technik",
    "batterien": "Elektro und Technik",
    "kabelkanal": "Elektro und Technik",
    "steckdosenleiste": "Elektro und Technik",
    "elektroverteiler": "Elektro und Technik",
    "funksteckdosen": "Elektro und Technik",
    "elektronikbauteile": "Elektro und Technik",
    "sicherungskasten": "Elektro und Technik",
    "elektromaterial": "Elektro und Technik",
    "badmöbel": "Bad und Küche",
    "duschkabine": "Bad und Küche",
    "waschbecken": "Bad und Küche",
    "küchenmöbel": "Bad und Küche",
    "armaturen": "Bad und Küche",
    "badaccessoires": "Bad und Küche",
    "spiegelschrank": "Bad und Küche",
    "badewanne": "Bad und Küche",
    "küchengeräte": "Bad und Küche",
    "spüle": "Bad und Küche",
    "toilette": "Bad und Küche",
    "küchenspüle": "Bad und Küche",
    "küchenarmatur": "Bad und Küche",
    "badezimmermöbel": "Bad und Küche",
    "duschvorhang": "Bad und Küche",
    "sofa": "Wohnen",
    "esstisch": "Wohnen",
    "wohnzimmermöbel": "Wohnen",
    "teppich": "Wohnen",
    "schlafzimmermöbel": "Wohnen",
    "couchtisch": "Wohnen",
    "sessel": "Wohnen",
    "wohnaccessoires": "Wohnen",
    "bettwäsche": "Wohnen",
    "wandregal": "Wohnen",
    "wohnzimmerschrank": "Wohnen",
    "kissen": "Wohnen",
    "lampen": "Wohnen",
    "bilder": "Wohnen",
    "vorhänge": "Wohnen",
    "campingausrüstung": "Freizeit",
    "zelte": "Freizeit",
    "outdoorbekleidung": "Freizeit",
    "sportgeräte": "Freizeit",
    "fahrrad": "Freizeit",
    "wanderausrüstung": "Freizeit",
    "campingmöbel": "Freizeit",
    "grillzubehör": "Freizeit",
    "schwimmbadzubehör": "Freizeit",
    "angelausrüstung": "Freizeit",
    "spielzeug": "Freizeit",
    "campinggeschirr": "Freizeit",
    "sonnenschutz": "Freizeit",
    "picknickset": "Freizeit",
    "campingstühle": "Freizeit",
    "hundefutter": "Tierwelt",
    "katzenstreu": "Tierwelt",
    "tierbedarf": "Tierwelt",
    "hundehalsband": "Tierwelt",
    "kratzbaum": "Tierwelt",
    "vogelkäfig": "Tierwelt",
    "aquarium": "Tierwelt",
    "kleintierkäfig": "Tierwelt",
    "tierfutter": "Tierwelt",
    "hundespielzeug": "Tierwelt",
    "katzenspielzeug": "Tierwelt",
    "nagerfutter": "Tierwelt",
    "hundekorb": "Tierwelt",
    "katzenklo": "Tierwelt",
    "haustierpflege": "Tierwelt"
}

mapping_drogerie  = {
    "tiernahrung": "Tiere",
    "hundefutter": "Tiere",
    "katzenfutter": "Tiere",
    "haustierbedarf": "Tiere",
    "tierzubehör": "Tiere",
    "haustierpflege": "Tiere",
    "tiermedizin": "Tiere",
    "tierkäfige": "Tiere",
    "vogelkäfig": "Tiere",
    "nagerfutter": "Tiere",
    "parfum": "Parfum",
    "parfümflasche": "Parfum",
    "damendüfte": "Parfum",
    "herrendüfte": "Parfum",
    "duft": "Parfum",
    "eau de": "Parfum",
    "makeup": "Makeup",
    "puder": "Makeup",
    "highlighter": "Makeup",
    "blush": "Makeup",
    "lidschadden": "Makeup",
    "kajal": "Makeup",
    "lippenstift": "Makeup",
    "mascara": "Makeup",
    "foundation": "Makeup",
    "rouge": "Makeup",
    "babywindeln": "Baby",
    "windel": "Baby",
    "wickeltasche": "Baby",
    "baby": "Baby",

    "babyöl": "Baby",
    "babybrei": "Baby",
    "babyspielzeug": "Baby",
    "babymode": "Baby",
    "lebensmittel": "Lebensmittel und Ernährung",
    "lebensmittelgeschäft": "Lebensmittel und Ernährung",
    "biolebensmittel": "Lebensmittel und Ernährung",
    "frischeprodukte": "Lebensmittel und Ernährung",
    "veganeprodukte": "Lebensmittel und Ernährung",
    "hygieneprodukte": "Hygiene",
    "toilettenpapier": "Hygiene",
    "handdesinfektionsmittel": "Hygiene",
    "seife": "Hygiene",
    "gesichtsmasken": "Hygiene",
    "deo": "Hygiene",
    "rasierer": "Hygiene",
    "shampoo": "Hygiene",
    "zahn": "Hygiene",
    "dusch": "Hygiene",
    "fotokameras": "Foto",
    "fotografieausrüstung": "Foto",
    "kameraobjektive": "Foto",
    "fotostudio": "Foto",
    "gesundheit": "Gesundheit",
    "vitamine": "Gesundheit",
    "schnupfen": "Gesundheit",
    "durchfall": "Gesundheit",
    "husten": "Gesundheit",
    "grippe": "Gesundheit",
    "magen": "Gesundheit",
    "fieber": "Gesundheit",
    "pflaster": "Gesundheit",
    "schmerzmittel": "Gesundheit",
    "nahrungsergänzungsmittel": "Gesundheit",
    "medizinprodukte": "Gesundheit",
     "apfel" : "Obst",
    "äpfel" : "Obst",
    "banane" : "Obst",
    "birne" : "Obst",
    "avocado" : "Obst",
    "erdbeere" : "Obst",
    "orange" : "Obst",
    "traube" : "Obst",
    "kirsche" : "Obst",
    "beeren" : "Obst",
    "ananas" : "Obst",
    "mango" : "Obst",
    "melone" : "Obst",
    "limette" : "Obst",
    "zitrone" : "Obst",
    "pfirsich" : "Obst",
    "gurke" : "Gemüse",
    "zwiebel" : "Gemüse",
    "tomate" : "Gemüse",
    "kartoffel" : "Gemüse",
    "karotte" : "Gemüse",
    "kohl" : "Gemüse",
    "pilz" : "Gemüse",
    "erbse" : "Gemüse",
    "spinat" : "Gemüse",
    "brokkoli" : "Gemüse",
    "salat" : "Gemüse",
    "quark" : "Molkerei",
    "butter" : "Molkerei",
    "joghurt" : "Molkerei",
    "käse" : "Molkerei",
    "rahm" : "Molkerei",
    "sahne": "Molkerei",
    "oberst": "Molkerei",
    "eier" : "Food",
    "nudel" : "Food",
    "mehl": "Food",
    "öl" : "Food",
    "nutella" : "Food",
    "marmelade" : "Food",
    "honig" : "Food",
    "sosse" : "Food",
    "soße" : "Food",
    "brot" : "Food",
    "bröt" : "Food",
    "zucker" : "Food",
    "gewürz" : "Food",
    "konserv" : "Food",
    "papier" : "Non-Food",
    "parfum" : "Non-Food",
    "spül" : "Non-Food",
    "schnitzel" : "Fleisch",
    "brust" : "Fleisch",
    "kotelett" : "Fleisch",
    "steak" : "Fleisch",
    "schenkel" : "Fleisch",
    "speck" : "Fleisch",
    "wurst" : "Fleisch",
    "würst" : "Fleisch",
    "schinken" : "Fleisch",
    "salami" : "Fleisch",
    "wiener" : "Fleisch",
    "bauch" : "Fleisch",
    "fleisch" : "Fleisch",
    "hühnchen" : "Fleisch",
    "hähnchen" : "Fleisch",
    "huhn" : "Fleisch",
    "fisch" : "Fleisch",
    "lachs": "Fleisch",
    "hering": "Fleisch",
    "thunfisch": "Fleisch",
    "makrele": "Fleisch",
    "forelle": "Fleisch",
    "schokolade" : "Snacks",
    "gummibären" : "Snacks",
    "jumpys" : "Snacks",
    "chips" : "Snacks",
    "salzstangen" : "Snacks",
    "keks" : "Snacks",
    "flake" : "Snacks",
    "snack" : "Snacks",
    "pflanz" : "Pflanzen",
    "orchide" : "Pflanzen",
    "kaktus": "Pflanzen",
    "fanta" : "Getränke",
    "cola" : "Getränke",
    "saft" : "Getränke",
    "limonade" : "Getränke",
    "tee" : "Getränke",
    "wasser" : "Getränke",
    "shake" : "Getränke",
    "schorle" : "Getränke",
    "energy" : "Getränke",
    "getränk" : "Getränke",
    "bier" : "Getränke",
    "wodka" : "Getränke",
    "schnaps" : "Getränke",
    "likör" : "Getränke",
    "weinbr" : "Getränke"
}

mapping = {

    "apfel" : "Obst",
    "äpfel" : "Obst",
    "banane" : "Obst",
    "birne" : "Obst",
    "avocado" : "Obst",
    "erdbeere" : "Obst",
    "orange" : "Obst",
    "traube" : "Obst",
    "kirsche" : "Obst",
    "beeren" : "Obst",
    "ananas" : "Obst",
    "mango" : "Obst",
    "melone" : "Obst",
    "limette" : "Obst",
    "zitrone" : "Obst",
    "pfirsich" : "Obst",
    "gurke" : "Gemüse",
    "zwiebel" : "Gemüse",
    "tomate" : "Gemüse",
    "kartoffel" : "Gemüse",
    "karotte" : "Gemüse",
    "kohl" : "Gemüse",
    "pilz" : "Gemüse",
    "erbse" : "Gemüse",
    "spinat" : "Gemüse",
    "brokkoli" : "Gemüse",
    "salat" : "Gemüse",
    "quark" : "Molkerei",
    "butter" : "Molkerei",
    "joghurt" : "Molkerei",
    "käse" : "Molkerei",
    "rahm" : "Molkerei",
    "sahne": "Molkerei",
    "oberst": "Molkerei",
    "eier" : "Food",
    "nudel" : "Food",
    "mehl": "Food",
    "öl" : "Food",
    "nutella" : "Food",
    "marmelade" : "Food",
    "honig" : "Food",
    "sosse" : "Food",
    "soße" : "Food",
    "brot" : "Food",
    "bröt" : "Food",
    "zucker" : "Food",
    "gewürz" : "Food",
    "konserv" : "Food",
    "papier" : "Non-Food",
    "parfum" : "Non-Food",
    "spül" : "Non-Food",
    "schnitzel" : "Fleisch",
    "brust" : "Fleisch",
    "kotelett" : "Fleisch",
    "steak" : "Fleisch",
    "schenkel" : "Fleisch",
    "speck" : "Fleisch",
    "wurst" : "Fleisch",
    "würst" : "Fleisch",
    "schinken" : "Fleisch",
    "salami" : "Fleisch",
    "wiener" : "Fleisch",
    "bauch" : "Fleisch",
    "fleisch" : "Fleisch",
    "hühnchen" : "Fleisch",
    "hähnchen" : "Fleisch",
    "huhn" : "Fleisch",
    "fisch" : "Fleisch",
    "lachs": "Fleisch",
    "hering": "Fleisch",
    "thunfisch": "Fleisch",
    "makrele": "Fleisch",
    "forelle": "Fleisch",
    "schokolade" : "Snacks",
    "gummibären" : "Snacks",
    "jumpys" : "Snacks",
    "chips" : "Snacks",
    "salzstangen" : "Snacks",
    "keks" : "Snacks",
    "flake" : "Snacks",
    "snack" : "Snacks",
    "pflanz" : "Pflanzen",
    "orchide" : "Pflanzen",
    "kaktus": "Pflanzen",
    "fanta" : "Getränke",
    "cola" : "Getränke",
    "saft" : "Getränke",
    "limonade" : "Getränke",
    "tee" : "Getränke",
    "wasser" : "Getränke",
    "shake" : "Getränke",
    "schorle" : "Getränke",
    "energy" : "Getränke",
    "getränk" : "Getränke",
    "bier" : "Getränke",
    "wodka" : "Getränke",
    "schnaps" : "Getränke",
    "likör" : "Getränke",
    "weinbr" : "Getränke"
}

mapping_biocompany = {
    "Angebot" : "Angebot"
}

mapping_rewe = {
    "Rewe" : "Rewe",
    "API" : "API"
}

mapping_ikea = {
    "IKEA" : "IKEA",
    "API" : "API"
}

mapping_aldisued = {
    "ALDISUED" : "ALDISUED",
    "API" : "API"
}


mapping_mueller_api= {
    "Mueller" : "Mueller",
    "API" : "API"
}


mapping_fressnapf_api= {
    "Fressnapf" : "Fressnapf",
    "API" : "API"
}
mapping_babywalz_api= {
    "BabyWalz" : "BabyWalz",
    "API" : "API"
}

mapping_kaufland_api ={
    "tiernahrung": "Tiere",
    "tier" : "Tiere",
    "parfum": "Parfum",
    "makeup": "Makeup",
    "baby": "Baby",
    "lebensmittel": "Lebensmittel und Ernährung",
    "hygiene": "Hygiene",
    "toilettenpapier": "Hygiene",
    "fotokamera": "Elektronik",
    "gesundheit": "Gesundheit",
    "vitamine": "Gesundheit",
    "obst" : "Obst",
    "apfel" : "Obst",
    "gemüse" : "Gemüse",
    "quark" : "Molkerei",
    "milch" : "Molkerei",
    "eier" : "Food",
    "nudel" : "Food",
    "mehl": "Food",
    "öl" : "Food",
    "nutella" : "Food",
    "marmelade" : "Food",
    "sosse" : "Food",
    "gewürz" : "Food",
    "fleisch" : "Fleisch",
    "wurst" : "Fleisch",
    "Fisch": "Fisch",
    "schokolade" : "Snacks",
    "gummibären" : "Snacks",
    "chips" : "Snacks",
    "salzstangen" : "Snacks",
    "keks" : "Snacks",
    "pflanze" : "Pflanzen",
    "blume" : "Pflanzen",
    "orchide" : "Pflanzen",
    "cola" : "Getränke",
    "saft" : "Getränke",
    "limonade" : "Getränke",
    "tee" : "Getränke",
    "shake" : "Getränke",
    "energy" : "Getränke",
    "getränk" : "Getränke",
    "bier" : "Getränke",
    "wodka" : "Getränke",
    "schnaps" : "Getränke",
    "Handy" : "Elektronik",
    "Laptop" : "Elektronik",
    "Computer" : "Elektronik",
    "Tablet" : "Elektronik",
}

dummy_store_type= {
    "dummy" : "Dummy"
}
